# Generated by Django 3.1.7 on 2021-04-04 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_company_email'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('zip_code', models.CharField(max_length=12)),
                ('cpf', models.IntegerField()),
                ('people_qtd', models.IntegerField()),
                ('space_restriction', models.BooleanField()),
                ('need_waiter', models.BooleanField()),
                ('want_entrance', models.BooleanField()),
                ('budget_date', models.DateField(auto_now_add=True)),
                ('event_distance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('event_date', models.DateField()),
                ('duration_hours', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'BudgetHeader',
                'verbose_name_plural': 'BudgetsHeader',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('cost_person_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('cost_distance_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('cost_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('budget_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetheader')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.dish')),
            ],
            options={
                'verbose_name': 'BudgetItem',
                'verbose_name_plural': 'BudgetItems',
            },
        ),
    ]
