# Generated by Django 3.1.7 on 2021-04-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('qnt_per_people', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('cost_per_people', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('cost_per_distance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('principal_dish', models.BooleanField()),
                ('entrance_dish', models.BooleanField()),
                ('space_restriction', models.BooleanField()),
                ('image', models.ImageField(default='https://cdn.dribbble.com/users/1012566/screenshots/4187820/topic-2.jpg', max_length=500, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
            },
        ),
    ]
